### ISSUE TITLE
Add Glauert tip loss corrections

### ISSUE THREAD

**Issue by petebachant** [turbinesFoam/turbinesFoam#207]
These values will need to be read by a turbine, such that number of blades and TSR can be passed on to the blades via a new `endEffects` dict. The Glauert end effect factor will then need to be recomputed at each time step based on the tip flow angle, which can be done inside `actuatorLineSource`.  Should also make a derived version based on Shen et al. (2005). 

Will probably want to use an `actuatorLineSource::setEndEffectsCoeffs` method or something, in case tip speed ratio changes during a run. Can pass a `const` reference to the turbine `tipSpeedRatio_`.

## Updates

Have this working now for the Glauert corrections for the tips.

## TODO

- [x] Apply root losses
- [ ] Write a test to ensure `phi` calculation makes sense
- [x] Write a test to ensure the numerical value of the correction makes sense
- [x] Add Shen model

**Comment by petebachant** [comment]
This should probably be a subdictionary within `axialFlowTurbineALSource`:

```c++
endEffects
{
    active on;
    endEffectsModel Shen; // Glauert || Shen || liftingLine?
    ShenCoeffs
    {
        g 0.5; // Something like this
        // etc etc...
    }
}
```

These would be applied to the blades. The lifting line end effects model could be applied to individual actuator lines as well within those subdictionaries.

**Comment by mohsenboojari** [comment]
have you implemented this option in turbineFoam? is it ready to be used?

**Comment by petebachant** [comment]
It hasn't been implemented yet. If you get a chance to work on it, a pull request would be much appreciated

**Comment by petebachant** [comment]
Be sure to update https://github.com/turbinesFoam/turbinesFoam/wiki/SOWFA-comparison after this is done.

**Comment by petebachant** [comment]
Should turn off individual blade end effects models if a different model is selected for the rotor.

**Comment by petebachant** [comment]
To be clear, in the Glauert correction, `phi` is not the angle of attack, but the local angle of the wind with respect to the rotor plane. This means `F` must be set on an element-wise basis.

**Comment by petebachant** [comment]
Should tip and root loss corrections be separate options?

**Comment by petebachant** [comment]
Actually thinking the rotor-level end effects `subDict` should simple be passed on to  the elements, adding the number of blades along the way. May need to add rotor radius along the way, since the nondimensional tip and root distances are calculated with the blade span.

**Comment by petebachant** [comment]
Have this working now for the Glauert corrections for the tips.


## TODO

- [ ] Apply root losses
- [ ] Write a test to ensure `phi` calculation makes sense
- [ ] Write a test to ensure the numerical value of the correction makes sense
